### ISSUE TITLE
Clarification on the in-grid dates

### ISSUE THREAD

**Issue by Tele42** [MightyCreak/mesamatrix#45] opened 2015-03-23 17:36 UTC
It seems to me that the objective of listing the date of a change is to help visitors determine if their mesa version from X date has newly landed feature Y, or to make it easier to determine what extensions have less time in the wild. If that is the case, something is logically wrong with the displayed date for nvc0's ARB_gpu_shader_fp64.

**Comment by MightyCreak** [comment] 2015-03-23 17:51
The dates feature is fairly new and we're fixing the bugs as they come. I'll discuss with @Xenopathic to see what's wrong with the extensions dates.

Thank you!

**Comment by Xenopathic** [comment] 2015-03-23 18:02
@Tele42 Are you referring to the fact that the Mesa column lists a much more recent date than the nvc0 column? I had a suspicion that would be misleading: it is a result of the removal of swrast and r300 from GL3.txt: technically, the status on those items changed, so the matrix logs a 'modification' for the extension as a whole (aka the Mesa column) but not for the individual drivers. This should probably be fixed, so that a changed set of drivers does not affect the modified date for the core Mesa column.

**Comment by Tele42** [comment] 2015-03-23 18:31
@Xenopathic I'm seeing 2014-07-24 from http://cgit.freedesktop.org/mesa/mesa/commit/docs/GL3.txt?id=f8e4792b227544aefd45eb716091adb7409fa843 which is of little to no value to a visitor.

**Comment by Xenopathic** [comment] 2015-03-23 21:32
@Tele42 Surely that's the intended behaviour though? The date of authoring, aka the date of implementation? The date displayed on the matrix doesn't correlate with releases anyway - master only becomes a new major release series (aka 4.2.0), and new features never get merged into an existing release series (aka 4.1.8 or whatever).

The date was only there to act as an indication of when the work was completed, not when it was released.

**Comment by MightyCreak** [comment] 2015-03-23 22:11
I think @Tele42 is right. Maybe we should take the committer date instead of the author date, since it's the committer date that is important for the visitor of the site (i.e. he wants to know when it arrived in the master branch, not when it has been done on the developer's local machine).

**Comment by Xenopathic** [comment] 2015-03-23 22:25
@MightyCreak That might be a good idea, but I doubt it will help with the problem at hand. Even once merged to master, the code might not be released for a few releases, as a new feature never gets backported to stable release branches.

**Comment by MightyCreak** [comment] 2015-03-24 19:17
@Xenopathic Agreed, though it's still a step in the right direction ;)
Actually, for what you mention there is an issue opened for that that might fit for the problem here too: #22 (if we can display it in the commit list, we might also be able to say in which version a feature appeared)

But for what @Tele42 mentioned, I think it's only the fact that the dates seemed to mismatch the actual date that the user want to see. At least, when having the release date and the feature date, the user will be able to know if the feature is in the release or not. (not perfect, but it's a first pass! baby steps guys ;))

**Closed** 2015-03-24 22:10 UTC
Labels: bug
