### ISSUE TITLE
Spell out anvil, lavapipe, turnip and venus, instead of anv, lvp, tu & vn

### ISSUE THREAD

**Issue by Olf0** [MightyCreak/mesamatrix#192] opened 2021-03-24 22:53 UTC
#### Suggestion
Please spell out `anvil`, `lavapipe`, `turnip` and `venus` in the leaderboard tables and the big tables, instead of using `anv`, `lvp`, `tu` and `vn`.

#### Reasons
* The abbreviations `anv`, `lvp`, `tu` and `vn` are not widely used and known, hence displaying them in the user visible part of mesamatrix (i.e., its generated web page) contradicts its very purpose:
To inform concisely about the current API implementation state of various MESA drivers.

* They are already spelled out in the commit messages listed in the section "Last commits"!
Hence confusingly two different names are used in the generated mesamatrix page for references to these MESA drivers:
   - `anvil` versus `anv`
   - `lavapipe` versus `lvp`
   - `turnip` versus `tu`
   - `venus` versus `vn`

**Comment by Olf0** [comment] 2021-04-08 14:43
#### Side note
Because I am not fluent in PHP, I am not sure, if it is sufficient to alter these Vulkan driver names them here:
https://github.com/MightyCreak/mesamatrix/blob/master/lib/Parser/Constants.php#L71

**Comment by MightyCreak** [comment] 2021-04-08 16:50
To implement your suggestion, you'll need to create an abstraction between the current drivers names and the long names. This is because the current names are used to parse the features.txt file, so we'll still need them.

**Comment by Olf0** [comment] 2021-04-08 17:30
Well, in theory this is an MESA issue, as the aforementioned "reason 2" / inconsistency shows: The MESA authors usually spell out these three Vulkan driver names in their commit messages, but these drivers' "real" names in the repository are in the abbreviated form (which is hardly recognisable in the case of tu and lvp).

Still I think it would serve the very purpose of mesamatrix well to rectify this flaw (see "reason 1").

**Comment by MightyCreak** [comment] 2021-04-08 20:27
I agree with you that we could do something about it. I'm just saying that we can't simply change the Constants.php file because the contents of features.txt only use the abbreviated names (my algorithm doesn't use the commit description to feed the table).

**Comment by Olf0** [comment] 2021-04-08 23:48
Thank you.
This was my primary aim: Create awareness of this.
Side note: By the help of your explanation and my little understanding of PHP, I now see, that this needs some workaround, e.g. with a look-up table and a function using it to translate these strings.

**Comment by Olf0** [comment] 2021-09-23 19:47
Updated to include `venus` / `vn`.

**Comment by okias** [comment] 2023-01-30 23:37
Please, **AT LEAST** provide note somewhere into bottom of page, so we can use shortcuts as _CTRL-F_ to find it.

I work on Mesa, so I know lvp shortcut, but when I wanted to check turnip features, I **REALLY** didn't associated it with `tu` when using combo as CTRL-F turnip.

**Comment by MightyCreak** [comment] 2024-12-21 18:04
This is issue is too old. Closing it.

**Closed by MightyCreak** 2024-12-21 18:04 UTC

**Comment by Olf0** [comment] 2024-12-21 21:51
> This is issue is too old. Closing it.

Seriously?  "Still present, but too old" is your reason to close it?

So should I file it anew, so it becomes a "new" issue, again?

#### More seriously:
@MightyCreak, as the maintainer you sure have the freedom to decide that this is irrelevant from your perspective (that is slightly indicated by "closed as not planned"), but please name the reason concisely and honestly.
Or just reopen this issue (which would be my preference), because this flaw will not go away by closing the corresponding issue tracking it.  You once seemed to have agreed that this flaw constitutes a readability / interpretability issue for the primary audience of Mesamatrix, hence IMO it makes sense to keep on tracking this issue to allow for anyone to easily find it and work on it (for this an [implementation route was coarsely described](https://github.com/MightyCreak/mesamatrix/issues/192#issuecomment-816305553): e.g. with a look-up table and a function using it to translate these strings).

Thanks!

**Comment by MightyCreak** [comment] 2024-12-24 05:40
I appreciate the passion you have for this project, but this issue is indeed old (almost 4 years), and no one stepped up and proposed a PR.

I understand that closing an issue doesn't fix it, but it simply has reached its expiration date.

There is no need to create a new issue and duplicate this one, but if you want, you can propose a PR to try and fix it, that would be more productive. When it happens, I'll link the issue and the PR.

I a project, issues do get closed, even if they are not addressed. It's part of their lifecycle. I see no use in leaving issues to rot. If the issue is really important, someone, or maybe me one day, will take the time to address it, whether or not there is an opened issue.
