### ISSUE TITLE
Minor UI: commit text overlaps leaderboard

### ISSUE THREAD

**Issue by clbr** [MightyCreak/mesamatrix#114] opened 2016-10-02 07:39 UTC
Using a browser window about 1500 pixels wide, the long commits overlap the leaderboard.

![Imgur](http://i.imgur.com/EN3JwEL.png)

**Comment by MightyCreak** [comment] 2016-10-02 18:04
Thanks! I'll see what I can do about that.

**Comment by bstaletic** [comment] 2016-12-03 17:55
I've been seeing this on firefox, but not on webkit based browsers. With webkit Leaderboard is displayed below Last commits.

**Comment by MightyCreak** [comment] 2016-12-03 18:29
@clbr @bstaletic What's your browser, their version and your OS?

I can't reproduce it neither on Fedora 25 nor OS X with Firefox 50.0.2 (I just realized that I don't have access to Windows anymore ;) ). I also tried on Safari 10.0.1 and got the same result.

I wanted to try on Web (the GNOME browser), but their is a bug apparently... nothing is displayed at all.

**Comment by bstaletic** [comment] 2016-12-03 18:44
That's odd, right now I can't reproduce it as well, but I'm certain I have seen what the screenshot shows. Maybe a browser upgrade fixed the issue. I have upgraded from icecat 38.8.0 to icecat 45.5.1. I'm on Arch linux. I also tried with palemoon 27.0.2 and qutebrowser git build. Icecat and palemoon are both firefox forks, while qutebrowset is based on pyqt and either qtwebkit or qtwebengine. All of these render the page properly now.

**Comment by MightyCreak** [comment] 2016-12-03 20:31
Since I'm using a more modern CSS feature called [flexbox](http://caniuse.com/#feat=flexbox), and although it's been supported since quite a few versions (click on "Shaw all"), I know there's been a few bugs in the implementation among these versions. Now it's quite stable though.

Since mesamatrix.net is a pretty niche website and a pet project, I didn't really care about browsers compatibility and wanted to test the new shiny things :D

I'll close this issue since it seems that you just need to have a modern browser to fix it.

Thanks! ;)

**Closed by MightyCreak** 2016-12-03 20:31 UTC
Labels: bug

**Comment by clbr** [comment] 2016-12-04 09:05
I'm using Fifth on Linux, FWIW. It does not support the flexbox in this Webkit version, it appears.
